### PR TITLE
[WIP] Switch to base toolkit package

### LINKED ISSUE #6: Depend on `openff-toolkit-base`?
### Comment:

Would you consider a change of `'s/openff-toolkit/openff-toolkit-base/'`? It'd be nice to be able to use NAGL alongside RDKit and/or OpenEye Toolkits but without AmberTools.

I poked around the repo (of the source code, not the feedstock) and didn't find any obvious AmberTools dependency. Not sure if there are other technical details.

### PR DESCRIPTION
**Pull request by mattwthompson**
Resolves #6 

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mattwthompson** [comment]
@conda-forge-admin, please rerender

**Comment by mattwthompson** [comment]
I've seen this error before. I forget how I fixed it. I'll come back to this later.

```
2023-06-07T19:48:44.3180221Z import: 'openff.nagl'
2023-06-07T19:48:46.9120512Z Traceback (most recent call last):
2023-06-07T19:48:46.9121926Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/test_tmp/run_test.py", line 2, in <module>
2023-06-07T19:48:46.9122469Z     import openff.nagl
2023-06-07T19:48:46.9169519Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/__init__.py", line 6, in <module>
2023-06-07T19:48:46.9170137Z     from openff.nagl.nn._models import GNNModel
2023-06-07T19:48:46.9170845Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/nn/__init__.py", line 7, in <module>
2023-06-07T19:48:46.9171273Z     from ._containers import ConvolutionModule, ReadoutModule
2023-06-07T19:48:46.9171963Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/nn/_containers.py", line 6, in <module>
2023-06-07T19:48:46.9172395Z     from openff.nagl.molecule._dgl import DGLMolecule, DGLMoleculeBatch
2023-06-07T19:48:46.9173107Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/molecule/__init__.py", line 5, in <module>
2023-06-07T19:48:46.9173490Z     from ._dgl.molecule import DGLMolecule
2023-06-07T19:48:46.9174188Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/molecule/_dgl/__init__.py", line 1, in <module>
2023-06-07T19:48:46.9174594Z     from .batch import DGLMoleculeBatch
2023-06-07T19:48:46.9175269Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/molecule/_dgl/batch.py", line 5, in <module>
2023-06-07T19:48:46.9175667Z     from .molecule import DGLBase, DGLMolecule
2023-06-07T19:48:46.9176376Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/nagl/molecule/_dgl/molecule.py", line 4, in <module>
2023-06-07T19:48:46.9176799Z     from openff.toolkit.topology.molecule import Molecule as OFFMolecule
2023-06-07T19:48:46.9177726Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/toolkit/topology/__init__.py", line 1, in <module>
2023-06-07T19:48:46.9178230Z     from openff.toolkit.topology.molecule import (
2023-06-07T19:48:46.9178949Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/toolkit/topology/molecule.py", line 57, in <module>
2023-06-07T19:48:46.9179367Z     from openff.toolkit.utils.constants import DEFAULT_AROMATICITY_MODEL
2023-06-07T19:48:46.9180083Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/toolkit/utils/__init__.py", line 9, in <module>
2023-06-07T19:48:46.9180488Z     from openff.toolkit.utils.toolkits import (
2023-06-07T19:48:46.9181173Z   File "/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/toolkit/utils/toolkits.py", line 134, in <module>
2023-06-07T19:48:46.9181620Z     from openff.toolkit.utils import all_subclasses
2023-06-07T19:48:46.9182488Z ImportError: cannot import name 'all_subclasses' from partially initialized module 'openff.toolkit.utils' (most likely due to a circular import) (/home/conda/feedstock_root/build_artifacts/openff-nagl_1686167106821/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.11/site-packages/openff/toolkit/utils/__init__.py)

**Comment by lilyminium** [comment]
Thanks Matt :) That's the best commit message I've ever seen!

**Comment by mattwthompson** [comment]
all chatGPT - there were a couple of edgier ones I passed on 🙃

**Comment by lilyminium** [comment]
I think this has been superseded by #11. #11 does include rdkit as a required dependency, which we could remove in the future -- looks this error was the same as the one in https://github.com/conda-forge/openff-fragmenter-feedstock/pull/7#issuecomment-1668505500 and is therefore resolved by the new toolkit release.

**Comment by mattwthompson** [comment]
Aha ... this must be what I was thinking of!

**Pull request closed without merging**
